'use client';
import React from 'react';

interface Feature {
    title: string;
    description: string;
    icon: string;
    color: string;
}

const features: Feature[] = [
    { title: 'SWE-1.5 Free', description: 'Near-frontier model, replacing SWE-1 as default. Free for all users through March 2026.', icon: '🧠', color: 'var(--color-primary)' },
    { title: 'Arena Mode', description: 'Blind AI model comparison inside your IDE with hidden identities and voting.', icon: '⚔️', color: 'var(--color-accent)' },
    { title: 'Parallel Agents', description: 'True parallel multi-agent sessions via Git worktrees to prevent merge conflicts.', icon: '🔄', color: 'var(--color-cta)' },
    { title: 'Fast Context', description: 'SWE-grep for 10–20× faster code retrieval, grabbing codebase understanding instantly.', icon: '⚡', color: '#f59e0b' },
    { title: 'Codemaps', description: 'Visual, persistent codebase navigation mapping architecture relationships (Beta).', icon: '🗺️', color: '#10b981' },
    { title: 'Plan Mode', description: 'Structured task planning generated by Cascade before code generation begins.', icon: '📋', color: '#6366f1' },
    { title: 'Hooks & MDM', description: 'Custom command execution and enterprise policy deployment support.', icon: '🔗', color: '#8b5cf6' },
    { title: 'Context Indicator', description: 'Visual bar to monitor context usage and anticipate AI degradation limits.', icon: '📊', color: '#ec4899' },
];

const WindsurfWave13FeatureGrid: React.FC = () => {
    return (
        <div style={{ margin: 'var(--space-10) 0' }}>
            <div className="grid grid-2" style={{ gap: 'var(--space-4)' }}>
                {features.map((feature, i) => (
                    <div
                        key={i}
                        className="hud-border transition"
                        style={{
                            padding: 'var(--space-6)',
                            backgroundColor: 'var(--color-surface)',
                            display: 'flex',
                            flexDirection: 'column',
                            gap: 'var(--space-3)',
                            borderLeft: `4px solid ${feature.color}`,
                            boxShadow: 'var(--shadow-lg)'
                        }}
                    >
                        <div className="flex items-center gap-3">
                            <span style={{ fontSize: 'var(--text-3xl)' }}>{feature.icon}</span>
                            <h4 style={{ margin: 0, color: 'var(--color-text-primary)' }}>{feature.title}</h4>
                        </div>
                        <p className="card-description" style={{ margin: 0 }}>
                            {feature.description}
                        </p>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default WindsurfWave13FeatureGrid;
